### ISSUE TITLE
Implement user-defined grid size

### ISSUE THREAD

**Issue by EricESeitz** [CompSciLauren/minesweeper#7]
I've been playing around with objects in JavaScript and HTML, what I'm having trouble figuring out is how we're going to implement the user-defined size.

Broadly, we'll have to make some sort of n x n grid and populate it with 'buttons'? Am I right in thinking this way?

**Comment by CompSciLauren** [comment]
Okay I honestly can't remember what the purpose of the user-defined size is in the game. In the one version I ever played, grid sizes were pre-determined based on difficulty level. Is that what we want? Or is this the part where you're saying we could have the user choose the grid size?

I think both options are perfectly good. One is easier than the other. I think one possible solution is to choose the easier route for now: pre-defined grids based on difficulty level. As an "enhancement" to do after we have met the requirements, we could introduce a "custom" grid option where the user chooses the grid size.

Side note, we should probably have a list of the official project requirements. I think this could just be in the form of Issues like we've been doing so far, we just need to add them.

**Comment by EricESeitz** [comment]
> Or is this the part where you're saying we could have the user choose the grid size?

I'm baseing this off of the Project 1 requirements on Canvas
"Game Setup

    Board size (from user)
        Must be at least 2x2
    Number mines (from user)
        Min: 1
        Max: number of squares - 1
    Randomly place the mines"

What this says to me is the user will enter a board size (i.e Input Board Size: 8. This makes an 8 x 8 board) and the number of mines to be put on the board (no less than 1, no more than n-1 of previous input)

What do you think?

**Comment by CompSciLauren** [comment]
Okay I think I've got it. So creating the grid doesn't need to be recursive like I originally thought. I think the recursive function is going to come into play for the algorithm that will explore the map to check for bombs/reveal spaces as the user clicks.

We should create a nested for loop! The first for-loop is for the row count, and the second for-loop is for the column-count. It will be similar to how the third exercise in Chapter 2 of Eloquent JavaScript is completed (the Chessboard one).

Does anyone want to take this Issue? I will un-assign us all from this Issue (currently 3 of us are "assigned" since it needed to be discussed). I figure the first person to assign themselves this Issue can be the one to complete it.

If anyone is opposed to any of this, please comment what you think!

**Comment by EricESeitz** [comment]
> We should create a nested for loop! The first for-loop is for the row count, and the second for-loop is for the column-count. It will be similar to how the third exercise in Chapter 2 of Eloquent JavaScript is completed (the Chessboard one).

I had a similar idea, actually I was just researching it and was playing around with this snippit of code: 
https://stackoverflow.com/questions/966225/how-can-i-create-a-two-dimensional-array-in-javascript/966938#966938

Some good suggestions there if you want some other ideas, as long as we credit I think it's ok to use small snippits like this. I could double-check with the Prof. though.

I guess you'll take this one and I can work on how to create the 'front-end' grid of buttons you'll see on the page.

**Comment by CompSciLauren** [comment]
Lollll all good! Yep that's what I'm talking about. So when I'm done with this Issue, on the website you will be able to create the grid and see basically a picture of all the squares, but they're all white squares in the form of a grid that don't do jack squat yet.

So if I have this right, then when you and I are done with this stuff, we'll be ready to "tie together" my grid picture on the website with your 2D array logic. That part itself would be a new Issue. Am I thinking of this the right way, or can you explain if you know of a different/better strategy?

**Comment by EricESeitz** [comment]
> You were probably already going to do this, but can you create a new Issue for the 2D array you're going to do?

Good idea, just created a new issue for the 2D array. Take a peak at it since I typed out the logic I have in my head and double-check if I make sense or not.

Basically, yeah. If what I have planned works all the squares will need to do is pass in a coordinate set to the JavaScript functions. 
Which reminds me, can you set it up in some way so each square has their coordinates 'stored' or otherwise accessible to JavaScript? I'm thinking a main JavaScript function like clickRun(var x, var y) will be called upon clicking a square, the coordinates passed in that way.

**Comment by CompSciLauren** [comment]
Yeah I think I can do that! Okay sounds good.

**Comment by EricESeitz** [comment]
I took a peek at the user-defined grid size.

Grid generation looks pretty good, I have a couple of things though:
1) The minimum size has to be 2x2, should this be hard-coded?
2) Excessively-large sizes seem to 'generate' off the right side of the page w/o being able to scroll to them, only up and down.
3) We need some sort of clickable element. Could we overlay a button of the same size on top of each square on generation of it?

**Comment by CompSciLauren** [comment]
1. Yes, it should. I'll add that change to my code.
2. Ooh good catch. A couple of things:
    - So I hope I'm not using these two terms wrong, but I believe this is an issue of static vs. dynamic web pages. Whatever it's called, basically right now our website is "static" in the sense that it doesn't adapt well to screen sizes being adjusted, or even different screen sizes in general. We would need to make it "dynamic" so that as you adjust the screen, the grid changes with it. I was thinking this doesn't have to come with our array/grid Issues, like changing the site to be dynamic might be its own Issue since it involves some steps. Let me look into this a little more to make sure I know what I'm talking about. I need to recall/google steps for switching to a dynamic page.
  - Are we allowed to implement a grid size limit? Because I think we should. Don't think we need any over 9000 grids... what do you think?
  - We can also look into making the grid n x m in the sense that there could be more columns than rows, which would make sense for computer screens. Need to check if this would be okay given requirements though, Mr. Kline didn't technically specify if we couldn't do mxn instead of nxn, so maybe he'd allow it.
    - If you go to Google's Minesweeper it's a good example of what I mean by dynamic, the grid moves with the page to keep it in view even if you start to move the page's width to be smaller.
3. These squares are able to be made click-able already, we don't have to create buttons on top of it.

**Comment by Earving8** [comment]
2. There are multiple ways to make it dynamic. The easiest probably being to make the width and height of the squares by percentage rather than pixels, and probably setting a minimum and maximum size. Should be able to be done through the CSS.
3. To make them clickable just have it directly call a function on click. You can change the cursor when hovered over the squares with CSS also. You could probably also just have an event listener in the script to look for when the squares are clicked.

**Comment by EricESeitz** [comment]
@CompSciLauren 
I'm trying to combine your user-defined grid and the 2D array but I'm having trouble with working JavaScript.

Basically, I need the individual square elements to be clickable, I can this easily by changing the div to '<div onclick = ... >' but what I'm getting stuck on is how to access the unique attributes of each square.

What I was thinking is during each squareElement creation in the drawSquares function, could we assign an onClick to something like:
<div onclick = clickFunction(x_coordinate, y_coordinate;>

The above doesn't work of course, but that's the general idea. Could I have some help with implementing this?

Thanks

**Comment by CompSciLauren** [comment]
I can do that when I get home from work today (~6pm). I'll use JQuery and call a function when the class associated with the square Div is clicked. Then you can do what you need to with that function once it's set up! I'm at work so keeping this quick, hope the wording makes sense!

**Comment by Earving8** [comment]
I added this when you create the elements

squareElement.attr("onmousedown", "pressedSquare(id)");

and for a function
function pressedSquare(id){
    console.log( id + "Pressed!");
    $("#" + id).addClass("pressed");
}

**Comment by CompSciLauren** [comment]
Earving that works, I did it a bit differently, same idea though. I made some edits, please take a look and approve if you don't see any issues with it! Commit message explains what changed. Only side note is, JQuery script moved to bottom of HTML file because I accidentally had it at the top which is wrong.

**Comment by CompSciLauren** [comment]
Resolved by #23, closing
