### ISSUE TITLE
Graphics. Clickable Grid or HTML Square Shapes?

### ISSUE THREAD

**Issue by EricESeitz** [CompSciLauren/minesweeper#9]
I have a rather rudimentary knowledge of JavaScript and HTML so this is probably a super dumb-dumb baby question but how are we going to implement the 'game space' of minesweeper? Will we be making a grid of individual square 'objects' in html (i.e .square) or some sort of clickable grid, using ASCII characters to represent flags/bombs?

**Comment by CompSciLauren** [comment]
Not a dumb question at all. I think there are multiple ways. I haven't attempted anything yet, and still need to whiteboard it to really know what I'm trying to say, but here's my initial thought:

Lots of ways to do this, depends how we want to design it... let's say we want:
x individual squares for EASY board
y individual squares for MEDIUM board
z individual squares for HARD board

So the board size is pre-set, based on level difficulty. We could have an array of the squares, and the array size is already defined based on level difficulty. We need each square to have a unique id associated with it, since any can be a space/integer/bomb. The id will be automatically assigned based on position in array.

I think we should use elements to draw the squares. Again multiple ways to do.... but I know we can create squares using HTML/JS/JQuery. To start off, we want to keep the drawings simple. So like, "bomb" revealed could be a filled-in red square. An integer revealed is just a number (typed out just like you'd see in this chat: 1 2 3 etc.) inside a box. Empty box could be a light shade of gray. Untouched boxes are white. The whole board itself is a black-outlined giant square filled with those individual squares.

I'll look into this more (hopefully tomorrow!) and post another comment when I have a better idea of what I'm trying to say, but this is my current thinking on the idea.
